// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18046
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Cb.Payments.Specs.OrderServiceSpecs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetAListOfOrdersWhenRequestingWithValidCredentialsFeature : Xunit.IUseFixture<GetAListOfOrdersWhenRequestingWithValidCredentialsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Get A List of Orders When Requesting with Valid Credentials.feature"
#line hidden
        
        public GetAListOfOrdersWhenRequestingWithValidCredentialsFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Get A List of Orders When Requesting with Valid Credentials", "In order to process orders in my system\r\nAs an API user\r\nI want to receive a list" +
                    " of orders", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I have valid credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table1.AddRow(new string[] {
                        "2012-09-26T18:02:34-07:00",
                        "BZH3EJ28",
                        "",
                        "MSTR",
                        "SALE",
                        "400",
                        "49.73",
                        "FITCOOKING",
                        "BENGEARY",
                        "PH",
                        "",
                        "",
                        "",
                        "PHP",
                        "",
                        "1605",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "0.01",
                        "AFFILIATE",
                        "",
                        "Metabolic Cooking Fat Loss Cookbooks Package",
                        "false",
                        "false"});
            table1.AddRow(new string[] {
                        "2012-10-16T11:41:17-07:00",
                        "9L2LWNE3",
                        "",
                        "VISA",
                        "SALE",
                        "6",
                        "37.00",
                        "NUMDIET",
                        "OUTRAGEOUS",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "33146",
                        "",
                        "",
                        "",
                        "37.00",
                        "2",
                        "0",
                        "2012-12-16T11:41:17-08:00",
                        "COMPLETED",
                        "8.30",
                        "VENDOR",
                        "Christine Example",
                        "Numerology Yoga: Web-Only Discount Special!",
                        "true",
                        "false"});
            table1.AddRow(new string[] {
                        "2012-11-19T10:23:45-08:00",
                        "PLWFEJZQ",
                        "",
                        "VISA",
                        "SALE",
                        "46",
                        "51.05",
                        "EODDIET",
                        "GODFREE120",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "11741",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.54",
                        "VENDOR",
                        "Christine Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table1.AddRow(new string[] {
                        "2012-11-24T09:46:46-08:00",
                        "GVP8EJPW",
                        "",
                        "VISA",
                        "SALE",
                        "51",
                        "1.00",
                        "EODDIET",
                        "JKFJKF",
                        "US",
                        "CA",
                        "EXAMPLE",
                        "RICK",
                        "USD",
                        "rick@example.com",
                        "95624",
                        "",
                        "",
                        "",
                        "46.00",
                        "1",
                        "1",
                        "2012-12-15T09:46:54-08:00",
                        "CANCELED",
                        "0.00",
                        "VENDOR",
                        "Rick Example",
                        "The EODD Trial Package With Radical Fat Loss Blueprint",
                        "true",
                        "false"});
            table1.AddRow(new string[] {
                        "2012-11-25T15:52:38-08:00",
                        "H74LFE5N",
                        "",
                        "PYPL",
                        "SALE",
                        "46",
                        "47.00",
                        "EODDIET",
                        "2010SOLU",
                        "US",
                        "WA",
                        "EXAMPLE",
                        "PETER",
                        "USD",
                        "peter@example.com",
                        "98155",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.62",
                        "VENDOR",
                        "Peter Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table1.AddRow(new string[] {
                        "2013-01-07T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "RFND",
                        "1",
                        "-34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
            table1.AddRow(new string[] {
                        "2013-01-08T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "SALE",
                        "eodd",
                        "34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
#line 8
 testRunner.And("the following order details", ((string)(null)), table1, "And ");
#line hidden
        }
        
        public virtual void SetFixture(GetAListOfOrdersWhenRequestingWithValidCredentialsFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Get A List of Orders When Requesting with Valid Credentials")]
        [Xunit.TraitAttribute("Description", "Get a default list of orders")]
        public virtual void GetADefaultListOfOrders()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a default list of orders", new string[] {
                        "mytag"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 20
 testRunner.When("I request a list with no paramaters", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table2.AddRow(new string[] {
                        "2012-09-26T18:02:34-07:00",
                        "BZH3EJ28",
                        "",
                        "MSTR",
                        "SALE",
                        "400",
                        "49.73",
                        "FITCOOKING",
                        "BENGEARY",
                        "PH",
                        "",
                        "",
                        "",
                        "PHP",
                        "",
                        "1605",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "0.01",
                        "AFFILIATE",
                        "",
                        "Metabolic Cooking Fat Loss Cookbooks Package",
                        "false",
                        "false"});
            table2.AddRow(new string[] {
                        "2012-10-16T11:41:17-07:00",
                        "9L2LWNE3",
                        "",
                        "VISA",
                        "SALE",
                        "6",
                        "37.00",
                        "NUMDIET",
                        "OUTRAGEOUS",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "33146",
                        "",
                        "",
                        "",
                        "37.00",
                        "2",
                        "0",
                        "2012-12-16T11:41:17-08:00",
                        "COMPLETED",
                        "8.30",
                        "VENDOR",
                        "Christine Example",
                        "Numerology Yoga: Web-Only Discount Special!",
                        "true",
                        "false"});
            table2.AddRow(new string[] {
                        "2012-11-19T10:23:45-08:00",
                        "PLWFEJZQ",
                        "",
                        "VISA",
                        "SALE",
                        "46",
                        "51.05",
                        "EODDIET",
                        "GODFREE120",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "11741",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.54",
                        "VENDOR",
                        "Christine Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table2.AddRow(new string[] {
                        "2012-11-24T09:46:46-08:00",
                        "GVP8EJPW",
                        "",
                        "VISA",
                        "SALE",
                        "51",
                        "1.00",
                        "EODDIET",
                        "JKFJKF",
                        "US",
                        "CA",
                        "EXAMPLE",
                        "RICK",
                        "USD",
                        "rick@example.com",
                        "95624",
                        "",
                        "",
                        "",
                        "46.00",
                        "1",
                        "1",
                        "2012-12-15T09:46:54-08:00",
                        "CANCELED",
                        "0.00",
                        "VENDOR",
                        "Rick Example",
                        "The EODD Trial Package With Radical Fat Loss Blueprint",
                        "true",
                        "false"});
            table2.AddRow(new string[] {
                        "2012-11-25T15:52:38-08:00",
                        "H74LFE5N",
                        "",
                        "PYPL",
                        "SALE",
                        "46",
                        "47.00",
                        "EODDIET",
                        "2010SOLU",
                        "US",
                        "WA",
                        "EXAMPLE",
                        "PETER",
                        "USD",
                        "peter@example.com",
                        "98155",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.62",
                        "VENDOR",
                        "Peter Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table2.AddRow(new string[] {
                        "2013-01-07T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "RFND",
                        "1",
                        "-34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
            table2.AddRow(new string[] {
                        "2013-01-08T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "SALE",
                        "eodd",
                        "34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
#line 21
 testRunner.Then("I should receive the following", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Get A List of Orders When Requesting with Valid Credentials")]
        [Xunit.TraitAttribute("Description", "Get a list of orders with a start date")]
        public virtual void GetAListOfOrdersWithAStartDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a list of orders with a start date", new string[] {
                        "mytag"});
#line 32
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 33
 testRunner.When("I request a list with a \'startDate\' of \'2012-11-19\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table3.AddRow(new string[] {
                        "2012-11-19T10:23:45-08:00",
                        "PLWFEJZQ",
                        "",
                        "VISA",
                        "SALE",
                        "46",
                        "51.05",
                        "EODDIET",
                        "GODFREE120",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "11741",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.54",
                        "VENDOR",
                        "Christine Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table3.AddRow(new string[] {
                        "2012-11-24T09:46:46-08:00",
                        "GVP8EJPW",
                        "",
                        "VISA",
                        "SALE",
                        "51",
                        "1.00",
                        "EODDIET",
                        "JKFJKF",
                        "US",
                        "CA",
                        "EXAMPLE",
                        "RICK",
                        "USD",
                        "rick@example.com",
                        "95624",
                        "",
                        "",
                        "",
                        "46.00",
                        "1",
                        "1",
                        "2012-12-15T09:46:54-08:00",
                        "CANCELED",
                        "0.00",
                        "VENDOR",
                        "Rick Example",
                        "The EODD Trial Package With Radical Fat Loss Blueprint",
                        "true",
                        "false"});
            table3.AddRow(new string[] {
                        "2012-11-25T15:52:38-08:00",
                        "H74LFE5N",
                        "",
                        "PYPL",
                        "SALE",
                        "46",
                        "47.00",
                        "EODDIET",
                        "2010SOLU",
                        "US",
                        "WA",
                        "EXAMPLE",
                        "PETER",
                        "USD",
                        "peter@example.com",
                        "98155",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.62",
                        "VENDOR",
                        "Peter Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table3.AddRow(new string[] {
                        "2013-01-07T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "RFND",
                        "1",
                        "-34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
#line 34
 testRunner.Then("I should receive the following", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Get A List of Orders When Requesting with Valid Credentials")]
        [Xunit.TraitAttribute("Description", "Get a list of orders between two dates")]
        public virtual void GetAListOfOrdersBetweenTwoDates()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a list of orders between two dates", new string[] {
                        "mytag"});
#line 42
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 43
 testRunner.When("I request a list with a \'startDate\' of \'2012-11-19\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
 testRunner.And("\'endDate\' of \'2012-11-25\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table4.AddRow(new string[] {
                        "2012-11-19T10:23:45-08:00",
                        "PLWFEJZQ",
                        "",
                        "VISA",
                        "SALE",
                        "46",
                        "51.05",
                        "EODDIET",
                        "GODFREE120",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "11741",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.54",
                        "VENDOR",
                        "Christine Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table4.AddRow(new string[] {
                        "2012-11-24T09:46:46-08:00",
                        "GVP8EJPW",
                        "",
                        "VISA",
                        "SALE",
                        "51",
                        "1.00",
                        "EODDIET",
                        "JKFJKF",
                        "US",
                        "CA",
                        "EXAMPLE",
                        "RICK",
                        "USD",
                        "rick@example.com",
                        "95624",
                        "",
                        "",
                        "",
                        "46.00",
                        "1",
                        "1",
                        "2012-12-15T09:46:54-08:00",
                        "CANCELED",
                        "0.00",
                        "VENDOR",
                        "Rick Example",
                        "The EODD Trial Package With Radical Fat Loss Blueprint",
                        "true",
                        "false"});
            table4.AddRow(new string[] {
                        "2012-11-25T15:52:38-08:00",
                        "H74LFE5N",
                        "",
                        "PYPL",
                        "SALE",
                        "46",
                        "47.00",
                        "EODDIET",
                        "2010SOLU",
                        "US",
                        "WA",
                        "EXAMPLE",
                        "PETER",
                        "USD",
                        "peter@example.com",
                        "98155",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.62",
                        "VENDOR",
                        "Peter Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
#line 45
 testRunner.Then("I should receive the following", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Get A List of Orders When Requesting with Valid Credentials")]
        [Xunit.TraitAttribute("Description", "Get a list of orders by email")]
        public virtual void GetAListOfOrdersByEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a list of orders by email", new string[] {
                        "mytag"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 53
 testRunner.When("I request a list with a \'email\' of \'peter@example.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table5.AddRow(new string[] {
                        "2012-10-16T11:41:17-07:00",
                        "9L2LWNE3",
                        "",
                        "VISA",
                        "SALE",
                        "6",
                        "37.00",
                        "NUMDIET",
                        "OUTRAGEOUS",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "33146",
                        "",
                        "",
                        "",
                        "37.00",
                        "2",
                        "0",
                        "2012-12-16T11:41:17-08:00",
                        "COMPLETED",
                        "8.30",
                        "VENDOR",
                        "Christine Example",
                        "Numerology Yoga: Web-Only Discount Special!",
                        "true",
                        "false"});
            table5.AddRow(new string[] {
                        "2012-11-19T10:23:45-08:00",
                        "PLWFEJZQ",
                        "",
                        "VISA",
                        "SALE",
                        "46",
                        "51.05",
                        "EODDIET",
                        "GODFREE120",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "11741",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.54",
                        "VENDOR",
                        "Christine Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
#line 54
 testRunner.Then("I should receive the following", ((string)(null)), table5, "Then ");
#line 58
 testRunner.When("I request a list with a email of \'test@example.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table6.AddRow(new string[] {
                        "2012-11-25T15:52:38-08:00",
                        "H74LFE5N",
                        "",
                        "PYPL",
                        "SALE",
                        "46",
                        "47.00",
                        "EODDIET",
                        "2010SOLU",
                        "US",
                        "WA",
                        "EXAMPLE",
                        "PETER",
                        "USD",
                        "peter@example.com",
                        "98155",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.62",
                        "VENDOR",
                        "Peter Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
#line 59
 testRunner.Then("I should receive the following", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Get A List of Orders When Requesting with Valid Credentials")]
        [Xunit.TraitAttribute("Description", "Get a list of orders by vendor")]
        public virtual void GetAListOfOrdersByVendor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a list of orders by vendor", new string[] {
                        "mytag"});
#line 64
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 65
 testRunner.When("I request a list with a \'vendor\' of \'eoddiet\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table7.AddRow(new string[] {
                        "2012-11-19T10:23:45-08:00",
                        "PLWFEJZQ",
                        "",
                        "VISA",
                        "SALE",
                        "46",
                        "51.05",
                        "EODDIET",
                        "GODFREE120",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "11741",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.54",
                        "VENDOR",
                        "Christine Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table7.AddRow(new string[] {
                        "2012-11-24T09:46:46-08:00",
                        "GVP8EJPW",
                        "",
                        "VISA",
                        "SALE",
                        "51",
                        "1.00",
                        "EODDIET",
                        "JKFJKF",
                        "US",
                        "CA",
                        "EXAMPLE",
                        "RICK",
                        "USD",
                        "rick@example.com",
                        "95624",
                        "",
                        "",
                        "",
                        "46.00",
                        "1",
                        "1",
                        "2012-12-15T09:46:54-08:00",
                        "CANCELED",
                        "0.00",
                        "VENDOR",
                        "Rick Example",
                        "The EODD Trial Package With Radical Fat Loss Blueprint",
                        "true",
                        "false"});
            table7.AddRow(new string[] {
                        "2012-11-25T15:52:38-08:00",
                        "H74LFE5N",
                        "",
                        "PYPL",
                        "SALE",
                        "46",
                        "47.00",
                        "EODDIET",
                        "2010SOLU",
                        "US",
                        "WA",
                        "EXAMPLE",
                        "PETER",
                        "USD",
                        "peter@example.com",
                        "98155",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.62",
                        "VENDOR",
                        "Peter Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
#line 66
 testRunner.Then("I should receive the following", ((string)(null)), table7, "Then ");
#line 71
 testRunner.When("I request a list with a \'vendor\' of \'numdiet\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table8.AddRow(new string[] {
                        "2012-10-16T11:41:17-07:00",
                        "9L2LWNE3",
                        "",
                        "VISA",
                        "SALE",
                        "6",
                        "37.00",
                        "NUMDIET",
                        "OUTRAGEOUS",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "33146",
                        "",
                        "",
                        "",
                        "37.00",
                        "2",
                        "0",
                        "2012-12-16T11:41:17-08:00",
                        "COMPLETED",
                        "8.30",
                        "VENDOR",
                        "Christine Example",
                        "Numerology Yoga: Web-Only Discount Special!",
                        "true",
                        "false"});
            table8.AddRow(new string[] {
                        "2013-01-07T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "RFND",
                        "1",
                        "-34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
            table8.AddRow(new string[] {
                        "2013-01-08T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "SALE",
                        "eodd",
                        "34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
#line 72
 testRunner.Then("I should receive the following", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Get A List of Orders When Requesting with Valid Credentials")]
        [Xunit.TraitAttribute("Description", "Get a list of orders by type")]
        public virtual void GetAListOfOrdersByType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a list of orders by type", new string[] {
                        "mytag"});
#line 79
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 80
 testRunner.When("I request a list with a \'txnType\' of \'SALE\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table9.AddRow(new string[] {
                        "2012-09-26T18:02:34-07:00",
                        "BZH3EJ28",
                        "",
                        "MSTR",
                        "SALE",
                        "400",
                        "49.73",
                        "FITCOOKING",
                        "BENGEARY",
                        "PH",
                        "",
                        "",
                        "",
                        "PHP",
                        "",
                        "1605",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "0.01",
                        "AFFILIATE",
                        "",
                        "Metabolic Cooking Fat Loss Cookbooks Package",
                        "false",
                        "false"});
            table9.AddRow(new string[] {
                        "2012-10-16T11:41:17-07:00",
                        "9L2LWNE3",
                        "",
                        "VISA",
                        "SALE",
                        "6",
                        "37.00",
                        "NUMDIET",
                        "OUTRAGEOUS",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "33146",
                        "",
                        "",
                        "",
                        "37.00",
                        "2",
                        "0",
                        "2012-12-16T11:41:17-08:00",
                        "COMPLETED",
                        "8.30",
                        "VENDOR",
                        "Christine Example",
                        "Numerology Yoga: Web-Only Discount Special!",
                        "true",
                        "false"});
            table9.AddRow(new string[] {
                        "2012-11-19T10:23:45-08:00",
                        "PLWFEJZQ",
                        "",
                        "VISA",
                        "SALE",
                        "46",
                        "51.05",
                        "EODDIET",
                        "GODFREE120",
                        "US",
                        "FL",
                        "EXAMPLE",
                        "CHRISTINE",
                        "USD",
                        "test@example.com",
                        "11741",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.54",
                        "VENDOR",
                        "Christine Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table9.AddRow(new string[] {
                        "2012-11-24T09:46:46-08:00",
                        "GVP8EJPW",
                        "",
                        "VISA",
                        "SALE",
                        "51",
                        "1.00",
                        "EODDIET",
                        "JKFJKF",
                        "US",
                        "CA",
                        "EXAMPLE",
                        "RICK",
                        "USD",
                        "rick@example.com",
                        "95624",
                        "",
                        "",
                        "",
                        "46.00",
                        "1",
                        "1",
                        "2012-12-15T09:46:54-08:00",
                        "CANCELED",
                        "0.00",
                        "VENDOR",
                        "Rick Example",
                        "The EODD Trial Package With Radical Fat Loss Blueprint",
                        "true",
                        "false"});
            table9.AddRow(new string[] {
                        "2012-11-25T15:52:38-08:00",
                        "H74LFE5N",
                        "",
                        "PYPL",
                        "SALE",
                        "46",
                        "47.00",
                        "EODDIET",
                        "2010SOLU",
                        "US",
                        "WA",
                        "EXAMPLE",
                        "PETER",
                        "USD",
                        "peter@example.com",
                        "98155",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "10.62",
                        "VENDOR",
                        "Peter Example",
                        "The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)",
                        "false",
                        "false"});
            table9.AddRow(new string[] {
                        "2013-01-08T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "SALE",
                        "eodd",
                        "34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
#line 81
 testRunner.Then("I should receive the following", ((string)(null)), table9, "Then ");
#line 89
 testRunner.When("I request a list with a \'txnType\' of \'RFND\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table10.AddRow(new string[] {
                        "2013-01-07T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "RFND",
                        "1",
                        "-34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
#line 90
 testRunner.Then("I should receive the following", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Get A List of Orders When Requesting with Valid Credentials")]
        [Xunit.TraitAttribute("Description", "Get a list of orders by type and role")]
        public virtual void GetAListOfOrdersByTypeAndRole()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get a list of orders by type and role", new string[] {
                        "mytag"});
#line 95
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 96
 testRunner.When("I request a list with a \'txnType\' of \'SALE\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
 testRunner.And("\'role\' of \'Affiliate\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "date",
                        "receipt",
                        "promo",
                        "pmtType",
                        "txnType",
                        "item",
                        "amount",
                        "site",
                        "affi",
                        "country",
                        "state",
                        "lastName",
                        "firstName",
                        "currency",
                        "email",
                        "zip",
                        "customerContactInfo",
                        "refundsBlocked",
                        "blockRefundReason",
                        "rebillAmount",
                        "processedPayments",
                        "futurePayments",
                        "nextPaymentDate",
                        "status",
                        "accountAmount",
                        "role",
                        "customerDisplayName",
                        "title",
                        "recurring",
                        "physical"});
            table11.AddRow(new string[] {
                        "2012-09-26T18:02:34-07:00",
                        "BZH3EJ28",
                        "",
                        "MSTR",
                        "SALE",
                        "400",
                        "49.73",
                        "FITCOOKING",
                        "BENGEARY",
                        "PH",
                        "",
                        "",
                        "",
                        "PHP",
                        "",
                        "1605",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "0.01",
                        "AFFILIATE",
                        "",
                        "Metabolic Cooking Fat Loss Cookbooks Package",
                        "false",
                        "false"});
            table11.AddRow(new string[] {
                        "2013-01-08T14:23:13-08:00",
                        "7698KM8E",
                        "",
                        "PYPL",
                        "SALE",
                        "eodd",
                        "34.26",
                        "NUMDIET",
                        "TTYLERAFF",
                        "GB",
                        "",
                        "",
                        "",
                        "GBP",
                        "",
                        "BS110HZ",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "-11.84",
                        "AFFILIATE",
                        "",
                        "The Numerology Diet - the Art and Science of Spiritual Eating",
                        "false",
                        "false"});
#line 98
 testRunner.Then("I should receive the following", ((string)(null)), table11, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GetAListOfOrdersWhenRequestingWithValidCredentialsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GetAListOfOrdersWhenRequestingWithValidCredentialsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
