Feature: Get A List of Orders When Requesting with Valid Credentials
	In order to process orders in my system
	As an API user
	I want to receive a list of orders

Background: 
	Given I have valid credentials
	And the following order details
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-09-26T18:02:34-07:00 | BZH3EJ28 |       | MSTR    | SALE    | 400  | 49.73  | FITCOOKING | BENGEARY   | PH      |       |          |           | PHP      |                   | 1605    |                     |                |                   |              |                   |                |                           |           | 0.01          | AFFILIATE |                     | Metabolic Cooking Fat Loss Cookbooks Package                  | false     | false    |
		| 2012-10-16T11:41:17-07:00 | 9L2LWNE3 |       | VISA    | SALE    | 6    | 37.00  | NUMDIET    | OUTRAGEOUS | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 33146   |                     |                |                   | 37.00        | 2                 | 0              | 2012-12-16T11:41:17-08:00 | COMPLETED | 8.30          | VENDOR    | Christine Example   | Numerology Yoga: Web-Only Discount Special!                   | true      | false    |
		| 2012-11-19T10:23:45-08:00 | PLWFEJZQ |       | VISA    | SALE    | 46   | 51.05  | EODDIET    | GODFREE120 | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 11741   |                     |                |                   |              |                   |                |                           |           | 10.54         | VENDOR    | Christine Example   | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2012-11-24T09:46:46-08:00 | GVP8EJPW |       | VISA    | SALE    | 51   | 1.00   | EODDIET    | JKFJKF     | US      | CA    | EXAMPLE  | RICK      | USD      | rick@example.com  | 95624   |                     |                |                   | 46.00        | 1                 | 1              | 2012-12-15T09:46:54-08:00 | CANCELED  | 0.00          | VENDOR    | Rick Example        | The EODD Trial Package With Radical Fat Loss Blueprint        | true      | false    |
		| 2012-11-25T15:52:38-08:00 | H74LFE5N |       | PYPL    | SALE    | 46   | 47.00  | EODDIET    | 2010SOLU   | US      | WA    | EXAMPLE  | PETER     | USD      | peter@example.com | 98155   |                     |                |                   |              |                   |                |                           |           | 10.62         | VENDOR    | Peter Example       | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2013-01-07T14:23:13-08:00 | 7698KM8E |       | PYPL    | RFND    | 1    | -34.26 | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |
		| 2013-01-08T14:23:13-08:00 | 7698KM8E |       | PYPL    | SALE    | eodd | 34.26  | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |

@mytag
Scenario: Get a default list of orders
	When I request a list with no paramaters
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-09-26T18:02:34-07:00 | BZH3EJ28 |       | MSTR    | SALE    | 400  | 49.73  | FITCOOKING | BENGEARY   | PH      |       |          |           | PHP      |                   | 1605    |                     |                |                   |              |                   |                |                           |           | 0.01          | AFFILIATE |                     | Metabolic Cooking Fat Loss Cookbooks Package                  | false     | false    |
		| 2012-10-16T11:41:17-07:00 | 9L2LWNE3 |       | VISA    | SALE    | 6    | 37.00  | NUMDIET    | OUTRAGEOUS | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 33146   |                     |                |                   | 37.00        | 2                 | 0              | 2012-12-16T11:41:17-08:00 | COMPLETED | 8.30          | VENDOR    | Christine Example   | Numerology Yoga: Web-Only Discount Special!                   | true      | false    |
		| 2012-11-19T10:23:45-08:00 | PLWFEJZQ |       | VISA    | SALE    | 46   | 51.05  | EODDIET    | GODFREE120 | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 11741   |                     |                |                   |              |                   |                |                           |           | 10.54         | VENDOR    | Christine Example   | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2012-11-24T09:46:46-08:00 | GVP8EJPW |       | VISA    | SALE    | 51   | 1.00   | EODDIET    | JKFJKF     | US      | CA    | EXAMPLE  | RICK      | USD      | rick@example.com  | 95624   |                     |                |                   | 46.00        | 1                 | 1              | 2012-12-15T09:46:54-08:00 | CANCELED  | 0.00          | VENDOR    | Rick Example        | The EODD Trial Package With Radical Fat Loss Blueprint        | true      | false    |
		| 2012-11-25T15:52:38-08:00 | H74LFE5N |       | PYPL    | SALE    | 46   | 47.00  | EODDIET    | 2010SOLU   | US      | WA    | EXAMPLE  | PETER     | USD      | peter@example.com | 98155   |                     |                |                   |              |                   |                |                           |           | 10.62         | VENDOR    | Peter Example       | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2013-01-07T14:23:13-08:00 | 7698KM8E |       | PYPL    | RFND    | 1    | -34.26 | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |
		| 2013-01-08T14:23:13-08:00 | 7698KM8E |       | PYPL    | SALE    | eodd | 34.26  | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |

@mytag
Scenario: Get a list of orders with a start date
	When I request a list with a 'startDate' of '2012-11-19' 
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-11-19T10:23:45-08:00 | PLWFEJZQ |       | VISA    | SALE    | 46   | 51.05  | EODDIET    | GODFREE120 | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 11741   |                     |                |                   |              |                   |                |                           |           | 10.54         | VENDOR    | Christine Example   | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2012-11-24T09:46:46-08:00 | GVP8EJPW |       | VISA    | SALE    | 51   | 1.00   | EODDIET    | JKFJKF     | US      | CA    | EXAMPLE  | RICK      | USD      | rick@example.com  | 95624   |                     |                |                   | 46.00        | 1                 | 1              | 2012-12-15T09:46:54-08:00 | CANCELED  | 0.00          | VENDOR    | Rick Example        | The EODD Trial Package With Radical Fat Loss Blueprint        | true      | false    |
		| 2012-11-25T15:52:38-08:00 | H74LFE5N |       | PYPL    | SALE    | 46   | 47.00  | EODDIET    | 2010SOLU   | US      | WA    | EXAMPLE  | PETER     | USD      | peter@example.com | 98155   |                     |                |                   |              |                   |                |                           |           | 10.62         | VENDOR    | Peter Example       | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2013-01-07T14:23:13-08:00 | 7698KM8E |       | PYPL    | RFND    | 1    | -34.26 | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |

@mytag
Scenario: Get a list of orders between two dates
	When I request a list with a 'startDate' of '2012-11-19' 
	And 'endDate' of '2012-11-25'
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-11-19T10:23:45-08:00 | PLWFEJZQ |       | VISA    | SALE    | 46   | 51.05  | EODDIET    | GODFREE120 | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 11741   |                     |                |                   |              |                   |                |                           |           | 10.54         | VENDOR    | Christine Example   | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2012-11-24T09:46:46-08:00 | GVP8EJPW |       | VISA    | SALE    | 51   | 1.00   | EODDIET    | JKFJKF     | US      | CA    | EXAMPLE  | RICK      | USD      | rick@example.com  | 95624   |                     |                |                   | 46.00        | 1                 | 1              | 2012-12-15T09:46:54-08:00 | CANCELED  | 0.00          | VENDOR    | Rick Example        | The EODD Trial Package With Radical Fat Loss Blueprint        | true      | false    |
		| 2012-11-25T15:52:38-08:00 | H74LFE5N |       | PYPL    | SALE    | 46   | 47.00  | EODDIET    | 2010SOLU   | US      | WA    | EXAMPLE  | PETER     | USD      | peter@example.com | 98155   |                     |                |                   |              |                   |                |                           |           | 10.62         | VENDOR    | Peter Example       | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		
@mytag
Scenario: Get a list of orders by email
	When I request a list with a 'email' of 'peter@example.com' 
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-10-16T11:41:17-07:00 | 9L2LWNE3 |       | VISA    | SALE    | 6    | 37.00  | NUMDIET    | OUTRAGEOUS | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 33146   |                     |                |                   | 37.00        | 2                 | 0              | 2012-12-16T11:41:17-08:00 | COMPLETED | 8.30          | VENDOR    | Christine Example   | Numerology Yoga: Web-Only Discount Special!                   | true      | false    |
		| 2012-11-19T10:23:45-08:00 | PLWFEJZQ |       | VISA    | SALE    | 46   | 51.05  | EODDIET    | GODFREE120 | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 11741   |                     |                |                   |              |                   |                |                           |           | 10.54         | VENDOR    | Christine Example   | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
	When I request a list with a email of 'test@example.com' 
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-11-25T15:52:38-08:00 | H74LFE5N |       | PYPL    | SALE    | 46   | 47.00  | EODDIET    | 2010SOLU   | US      | WA    | EXAMPLE  | PETER     | USD      | peter@example.com | 98155   |                     |                |                   |              |                   |                |                           |           | 10.62         | VENDOR    | Peter Example       | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
	
@mytag
Scenario: Get a list of orders by vendor
	When I request a list with a 'vendor' of 'eoddiet' 
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-11-19T10:23:45-08:00 | PLWFEJZQ |       | VISA    | SALE    | 46   | 51.05  | EODDIET    | GODFREE120 | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 11741   |                     |                |                   |              |                   |                |                           |           | 10.54         | VENDOR    | Christine Example   | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2012-11-24T09:46:46-08:00 | GVP8EJPW |       | VISA    | SALE    | 51   | 1.00   | EODDIET    | JKFJKF     | US      | CA    | EXAMPLE  | RICK      | USD      | rick@example.com  | 95624   |                     |                |                   | 46.00        | 1                 | 1              | 2012-12-15T09:46:54-08:00 | CANCELED  | 0.00          | VENDOR    | Rick Example        | The EODD Trial Package With Radical Fat Loss Blueprint        | true      | false    |
		| 2012-11-25T15:52:38-08:00 | H74LFE5N |       | PYPL    | SALE    | 46   | 47.00  | EODDIET    | 2010SOLU   | US      | WA    | EXAMPLE  | PETER     | USD      | peter@example.com | 98155   |                     |                |                   |              |                   |                |                           |           | 10.62         | VENDOR    | Peter Example       | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
	When I request a list with a 'vendor' of 'numdiet' 
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-10-16T11:41:17-07:00 | 9L2LWNE3 |       | VISA    | SALE    | 6    | 37.00  | NUMDIET    | OUTRAGEOUS | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 33146   |                     |                |                   | 37.00        | 2                 | 0              | 2012-12-16T11:41:17-08:00 | COMPLETED | 8.30          | VENDOR    | Christine Example   | Numerology Yoga: Web-Only Discount Special!                   | true      | false    |
		| 2013-01-07T14:23:13-08:00 | 7698KM8E |       | PYPL    | RFND    | 1    | -34.26 | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |
		| 2013-01-08T14:23:13-08:00 | 7698KM8E |       | PYPL    | SALE    | eodd | 34.26  | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |
	
@mytag
Scenario: Get a list of orders by type
	When I request a list with a 'txnType' of 'SALE' 
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-09-26T18:02:34-07:00 | BZH3EJ28 |       | MSTR    | SALE    | 400  | 49.73  | FITCOOKING | BENGEARY   | PH      |       |          |           | PHP      |                   | 1605    |                     |                |                   |              |                   |                |                           |           | 0.01          | AFFILIATE |                     | Metabolic Cooking Fat Loss Cookbooks Package                  | false     | false    |
		| 2012-10-16T11:41:17-07:00 | 9L2LWNE3 |       | VISA    | SALE    | 6    | 37.00  | NUMDIET    | OUTRAGEOUS | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 33146   |                     |                |                   | 37.00        | 2                 | 0              | 2012-12-16T11:41:17-08:00 | COMPLETED | 8.30          | VENDOR    | Christine Example   | Numerology Yoga: Web-Only Discount Special!                   | true      | false    |
		| 2012-11-19T10:23:45-08:00 | PLWFEJZQ |       | VISA    | SALE    | 46   | 51.05  | EODDIET    | GODFREE120 | US      | FL    | EXAMPLE  | CHRISTINE | USD      | test@example.com  | 11741   |                     |                |                   |              |                   |                |                           |           | 10.54         | VENDOR    | Christine Example   | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2012-11-24T09:46:46-08:00 | GVP8EJPW |       | VISA    | SALE    | 51   | 1.00   | EODDIET    | JKFJKF     | US      | CA    | EXAMPLE  | RICK      | USD      | rick@example.com  | 95624   |                     |                |                   | 46.00        | 1                 | 1              | 2012-12-15T09:46:54-08:00 | CANCELED  | 0.00          | VENDOR    | Rick Example        | The EODD Trial Package With Radical Fat Loss Blueprint        | true      | false    |
		| 2012-11-25T15:52:38-08:00 | H74LFE5N |       | PYPL    | SALE    | 46   | 47.00  | EODDIET    | 2010SOLU   | US      | WA    | EXAMPLE  | PETER     | USD      | peter@example.com | 98155   |                     |                |                   |              |                   |                |                           |           | 10.62         | VENDOR    | Peter Example       | The Every Other Day Diet 2.0: PDF Format (the SNAPP! System)  | false     | false    |
		| 2013-01-08T14:23:13-08:00 | 7698KM8E |       | PYPL    | SALE    | eodd | 34.26  | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |
	When I request a list with a 'txnType' of 'RFND' 
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2013-01-07T14:23:13-08:00 | 7698KM8E |       | PYPL    | RFND    | 1    | -34.26 | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |
	
@mytag
Scenario: Get a list of orders by type and role
	When I request a list with a 'txnType' of 'SALE' 
	And 'role' of 'Affiliate'
	Then I should receive the following
		| date                      | receipt  | promo | pmtType | txnType | item | amount | site       | affi       | country | state | lastName | firstName | currency | email             | zip     | customerContactInfo | refundsBlocked | blockRefundReason | rebillAmount | processedPayments | futurePayments | nextPaymentDate           | status    | accountAmount | role      | customerDisplayName | title                                                         | recurring | physical |
		| 2012-09-26T18:02:34-07:00 | BZH3EJ28 |       | MSTR    | SALE    | 400  | 49.73  | FITCOOKING | BENGEARY   | PH      |       |          |           | PHP      |                   | 1605    |                     |                |                   |              |                   |                |                           |           | 0.01          | AFFILIATE |                     | Metabolic Cooking Fat Loss Cookbooks Package                  | false     | false    |
		| 2013-01-08T14:23:13-08:00 | 7698KM8E |       | PYPL    | SALE    | eodd | 34.26  | NUMDIET    | TTYLERAFF  | GB      |       |          |           | GBP      |                   | BS110HZ |                     |                |                   |              |                   |                |                           |           | -11.84        | AFFILIATE |                     | The Numerology Diet - the Art and Science of Spiritual Eating | false     | false    |
